version: 2
report_sizes: true

before:
  hooks:
    - go mod tidy

gomod:
  proxy: true
  mod: mod
  env:
    - GOPROXY=https://proxy.golang.org,direct
    - GOSUMDB=sum.golang.org
    - GOPRIVATE=github.com/jimmystewpot/dns-preload

builds:
  - id: "dns-preload"
    main: ./cmd/dns-preload
    binary: "dns-preload"
    flags:
      - -trimpath
      - -buildvcs=true
    ldflags:
      - -w -s
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - freebsd
      - linux
      - netbsd
      - openbsd
      - windows

    goarch:
      - amd64
      - arm
      - arm64

    goarm:
      - "6"
      - "7"

    goamd64:
      - v2
      - v3

    ignore:
      - goos: darwin
        goarch: arm
        goarm: 6
      - goos: darwin
        goarch: arm
        goarm: 7


    mod_timestamp: "{{ .CommitTimestamp }}"
    skip: false
    no_unique_dist_dir: false
    no_main_check: true

checksum:
  name_template: '{{ .ArtifactName }}.{{ .Algorithm }}'
  algorithm: sha256
  split: true
  disable: false
  extra_files:
    - glob: LICENSE

release:
  mode: append
  skip_upload: false