name: Unit Test, Lint and Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: "1 1 2 * *"

permissions:
  pull-requests: read # allows SonarCloud to decorate PRs with analysis results

jobs:
  build_and_test:
    name: "Lint Test and Build"
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Test and Build
        run: make build

